/* Phone dialing codes — single source of truth, imported by both
   components/PreorderForm.tsx and components/InquiryForm.tsx (previously each
   kept its own short list, which silently blocked clients from un-listed
   countries at checkout).

   The selector renders code-only labels to stay narrow; `n` is the country
   name used for the React key and the option's hover title.

   Curated premium markets come first (Italy first, matching the studio), then
   a comprehensive set of remaining markets ordered so every realistic client
   can find their dialing code. Codes are unique — entries like +1 (US/Canada)
   and +7 (Russia/Kazakhstan) cover all countries that share that code. */
export type CountryCode = { code: string; n: string };

export const COUNTRY_CODES: CountryCode[] = [
  // — priority markets —
  { code: "+39", n: "Italy" },
  { code: "+1", n: "United States / Canada" },
  { code: "+44", n: "United Kingdom" },
  { code: "+33", n: "France" },
  { code: "+49", n: "Germany" },
  { code: "+34", n: "Spain" },
  { code: "+41", n: "Switzerland" },
  { code: "+31", n: "Netherlands" },
  { code: "+351", n: "Portugal" },
  { code: "+32", n: "Belgium" },
  { code: "+43", n: "Austria" },
  { code: "+353", n: "Ireland" },
  { code: "+45", n: "Denmark" },
  { code: "+46", n: "Sweden" },
  { code: "+47", n: "Norway" },
  { code: "+971", n: "United Arab Emirates" },
  { code: "+966", n: "Saudi Arabia" },
  { code: "+974", n: "Qatar" },
  { code: "+65", n: "Singapore" },
  { code: "+852", n: "Hong Kong" },
  { code: "+61", n: "Australia" },
  { code: "+81", n: "Japan" },
  { code: "+82", n: "South Korea" },
  { code: "+91", n: "India" },
  { code: "+55", n: "Brazil" },
  { code: "+52", n: "Mexico" },
  { code: "+90", n: "Turkey" },
  { code: "+27", n: "South Africa" },

  // — rest of Europe —
  { code: "+30", n: "Greece" },
  { code: "+36", n: "Hungary" },
  { code: "+40", n: "Romania" },
  { code: "+48", n: "Poland" },
  { code: "+420", n: "Czechia" },
  { code: "+421", n: "Slovakia" },
  { code: "+359", n: "Bulgaria" },
  { code: "+385", n: "Croatia" },
  { code: "+386", n: "Slovenia" },
  { code: "+381", n: "Serbia" },
  { code: "+382", n: "Montenegro" },
  { code: "+383", n: "Kosovo" },
  { code: "+387", n: "Bosnia and Herzegovina" },
  { code: "+389", n: "North Macedonia" },
  { code: "+355", n: "Albania" },
  { code: "+358", n: "Finland" },
  { code: "+354", n: "Iceland" },
  { code: "+372", n: "Estonia" },
  { code: "+371", n: "Latvia" },
  { code: "+370", n: "Lithuania" },
  { code: "+352", n: "Luxembourg" },
  { code: "+356", n: "Malta" },
  { code: "+357", n: "Cyprus" },
  { code: "+377", n: "Monaco" },
  { code: "+378", n: "San Marino" },
  { code: "+380", n: "Ukraine" },
  { code: "+375", n: "Belarus" },
  { code: "+373", n: "Moldova" },
  { code: "+7", n: "Russia / Kazakhstan" },
  { code: "+995", n: "Georgia" },
  { code: "+374", n: "Armenia" },
  { code: "+994", n: "Azerbaijan" },

  // — Middle East & South / Central Asia —
  { code: "+972", n: "Israel" },
  { code: "+962", n: "Jordan" },
  { code: "+961", n: "Lebanon" },
  { code: "+968", n: "Oman" },
  { code: "+973", n: "Bahrain" },
  { code: "+965", n: "Kuwait" },
  { code: "+964", n: "Iraq" },
  { code: "+98", n: "Iran" },
  { code: "+92", n: "Pakistan" },
  { code: "+93", n: "Afghanistan" },
  { code: "+880", n: "Bangladesh" },
  { code: "+94", n: "Sri Lanka" },
  { code: "+977", n: "Nepal" },
  { code: "+960", n: "Maldives" },

  // — East & Southeast Asia —
  { code: "+86", n: "China" },
  { code: "+886", n: "Taiwan" },
  { code: "+853", n: "Macau" },
  { code: "+62", n: "Indonesia" },
  { code: "+60", n: "Malaysia" },
  { code: "+66", n: "Thailand" },
  { code: "+84", n: "Vietnam" },
  { code: "+63", n: "Philippines" },
  { code: "+95", n: "Myanmar" },
  { code: "+855", n: "Cambodia" },
  { code: "+856", n: "Laos" },
  { code: "+673", n: "Brunei" },
  { code: "+976", n: "Mongolia" },

  // — Oceania —
  { code: "+64", n: "New Zealand" },
  { code: "+679", n: "Fiji" },
  { code: "+675", n: "Papua New Guinea" },

  // — Africa —
  { code: "+20", n: "Egypt" },
  { code: "+212", n: "Morocco" },
  { code: "+213", n: "Algeria" },
  { code: "+216", n: "Tunisia" },
  { code: "+218", n: "Libya" },
  { code: "+234", n: "Nigeria" },
  { code: "+254", n: "Kenya" },
  { code: "+233", n: "Ghana" },
  { code: "+255", n: "Tanzania" },
  { code: "+256", n: "Uganda" },
  { code: "+251", n: "Ethiopia" },
  { code: "+260", n: "Zambia" },
  { code: "+263", n: "Zimbabwe" },
  { code: "+225", n: "Côte d’Ivoire" },
  { code: "+221", n: "Senegal" },
  { code: "+237", n: "Cameroon" },
  { code: "+250", n: "Rwanda" },
  { code: "+244", n: "Angola" },
  { code: "+258", n: "Mozambique" },
  { code: "+267", n: "Botswana" },
  { code: "+230", n: "Mauritius" },

  // — Latin America —
  { code: "+54", n: "Argentina" },
  { code: "+56", n: "Chile" },
  { code: "+57", n: "Colombia" },
  { code: "+51", n: "Peru" },
  { code: "+58", n: "Venezuela" },
  { code: "+593", n: "Ecuador" },
  { code: "+591", n: "Bolivia" },
  { code: "+595", n: "Paraguay" },
  { code: "+598", n: "Uruguay" },
  { code: "+507", n: "Panama" },
  { code: "+506", n: "Costa Rica" },
  { code: "+502", n: "Guatemala" },
  { code: "+503", n: "El Salvador" },
  { code: "+504", n: "Honduras" },
  { code: "+505", n: "Nicaragua" },
  { code: "+53", n: "Cuba" },
  { code: "+509", n: "Haiti" },
];
